// import React, { useEffect, useState, useCallback } from 'react';

// export default class Controller {
//     static instance = Controller.instance || new Controller()

//     helloWorld() {
//         return [items, setItems] = useState([
//             { name: "", backgroundColor: "#008000", textColor: "#008000", pointsColor: "#008000", id: 0, pts: 10001 },
//             { name: "header + rodada_atual", backgroundColor: "#008000", textColor: "#fff", pointsColor: "#008000", id: 0, pts: 10000 },
        
//             { name: "5prastantas F.C.", slug: require("./src/assets/escudos/5prastantas-f-c.png"), backgroundColor: "#808080", textColor: "#ffffff", pointsColor: "#ffffff", id: 13945827, maiorPontuacao: 68, pontuacaoUltimaRodada: 68, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "AA AZULAO DO SUL", slug: require("./src/assets/escudos/aa-azulao-do-sul.png"), backgroundColor: "#ff241d", textColor: "#063780", pointsColor: "#063780", id: 6717458, maiorPontuacao: 25, pontuacaoUltimaRodada: 25, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Akuma Sport Club", slug: require("./src/assets/escudos/akuma-sport-club.png"), backgroundColor: "#ffffff", textColor: "#000000", pointsColor: "#000000", id: 483335, maiorPontuacao: 63, pontuacaoUltimaRodada: 63, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Atleticado", slug: require("./src/assets/escudos/atleticado.png"), backgroundColor: "#4d004d", textColor: "#0066ff", pointsColor: "#0066ff", id: 661306, maiorPontuacao: 65, pontuacaoUltimaRodada: 65, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Balacubacu FC", slug: require("./src/assets/escudos/balacubacu-fc.png"), backgroundColor: "#000000", textColor: "#808080", pointsColor: "#808080", id: 3170764, maiorPontuacao: 70, pontuacaoUltimaRodada: 70, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Bigode De Cartola", slug: require("./src/assets/escudos/bigode-de-cartola.png"), backgroundColor: "#997a00", textColor: "#ffffff", pointsColor: "#ffffff", id: 987444, maiorPontuacao: 65, pontuacaoUltimaRodada: 65, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "BOUGERS", slug: require("./src/assets/escudos/bougers.png"), backgroundColor: "#ff241d", textColor: "#000000", pointsColor: "#000000", id: 2835988, maiorPontuacao: 35, pontuacaoUltimaRodada: 35, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Calambau Beer", slug: require("./src/assets/escudos/calambau-beer.png"), backgroundColor: "#000000", textColor: "#ffffff", pointsColor: "#ffffff", id: 253542, maiorPontuacao: 34, pontuacaoUltimaRodada: 34, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Cangaceiros BF", slug: require("./src/assets/escudos/cangaceiros-bf.png"), backgroundColor: "#000000", textColor: "#19ff81", pointsColor: "#19ff81", id: 4554581, maiorPontuacao: 50, pontuacaoUltimaRodada: 50, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "ChristoFlamengo", slug: require("./src/assets/escudos/christoflamengo.png"), backgroundColor: "#bf1d17", textColor: "#000000", pointsColor: "#000000", id: 1540816, maiorPontuacao: 31, pontuacaoUltimaRodada: 31, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Código Fonte F.C", slug: require("./src/assets/escudos/codigo-fonte-f-c.png"), backgroundColor: "#ffffff", textColor: "#063780", pointsColor: "#063780", id: 2489031, maiorPontuacao: 37, pontuacaoUltimaRodada: 37, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Edu 07 Araxá", slug: require("./src/assets/escudos/edu-07-araxa.png"), backgroundColor: "#808080", textColor: "#ffffff", pointsColor: "#ffffff", id: 1225635, maiorPontuacao: 66, pontuacaoUltimaRodada: 66, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "El mordedô", slug: require("./src/assets/escudos/el-mordedo.png"), backgroundColor: "#4d004d", textColor: "#00cc5c", pointsColor: "#00cc5c", id: 25856343, maiorPontuacao: 75, pontuacaoUltimaRodada: 75, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Ganso Doido", slug: require("./src/assets/escudos/ganso-doido.png"), backgroundColor: "#bf1d17", textColor: "#063780", pointsColor: "#063780", id: 90144, maiorPontuacao: 54, pontuacaoUltimaRodada: 54, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "GastroNeles", slug: require("./src/assets/escudos/gastroneles.png"), backgroundColor: "#000000", textColor: "#ffffff", pointsColor: "#ffffff", id: 3438042, maiorPontuacao: 60, pontuacaoUltimaRodada: 60, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Golog", slug: require("./src/assets/escudos/golog.png"), backgroundColor: "#000000", textColor: "#ffcb00", pointsColor: "#ffcb00", id: 25872151, maiorPontuacao: 29, pontuacaoUltimaRodada: 29, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Leozito Neves FC", slug: require("./src/assets/escudos/leozito-neves-fc.png"), backgroundColor: "#000000", textColor: "#bf1d17", pointsColor: "#bf1d17", id: 4528687, maiorPontuacao: 34, pontuacaoUltimaRodada: 34, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "MBM Football", slug: require("./src/assets/escudos/mbm-football.png"), backgroundColor: "#ffffff", textColor: "#000000", pointsColor: "#000000", id: 8869919, maiorPontuacao: 69, pontuacaoUltimaRodada: 69, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Menino Esperto F. C.", slug: require("./src/assets/escudos/menino-esperto-f-c.png"), backgroundColor: "#000000", textColor: "#ffcb00", pointsColor: "#ffcb00", id: 7875842, maiorPontuacao: 56, pontuacaoUltimaRodada: 56, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Meninos do Maudi", slug: require("./src/assets/escudos/meninos-do-maudi.png"), backgroundColor: "#000000", textColor: "#ffffff", pointsColor: "#ffffff", id: 1179838, maiorPontuacao: 55, pontuacaoUltimaRodada: 55, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "MGuto FC", slug: require("./src/assets/escudos/mguto-fc.png"), backgroundColor: "#000000", textColor: "#ff241d", pointsColor: "#ff241d", id: 832153, maiorPontuacao: 54, pontuacaoUltimaRodada: 54, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Palla Sports", slug: require("./src/assets/escudos/palla-sports.png"), backgroundColor: "#808080", textColor: "#ff7400", pointsColor: "#ff7400", id: 623570, maiorPontuacao: 39, pontuacaoUltimaRodada: 39, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Pyranha", slug: require("./src/assets/escudos/pyranha.png"), backgroundColor: "#e65ce6", textColor: "#000000", pointsColor: "#000000", id: 1135503, maiorPontuacao: 42, pontuacaoUltimaRodada: 42, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "WolvenFootball", slug: require("./src/assets/escudos/wolvenfootball.png"), backgroundColor: "#ffffff", textColor: "#0a6634", pointsColor: "#0a6634", id: 634335, maiorPontuacao: 62, pontuacaoUltimaRodada: 62, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Sei de tudo e não ganho nada FC", slug: require("./src/assets/escudos/sei-de-tudo-e-nao-ganho-nada-fc.png"), backgroundColor: "#ff241d", textColor: "#19ff81", pointsColor: "#19ff81", id: 749772, maiorPontuacao: 51, pontuacaoUltimaRodada: 51, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Sheik Tosado FC", slug: require("./src/assets/escudos/sheik-tosado-fc.png"), backgroundColor: "#ff241d", textColor: "#000000", pointsColor: "#000000", id: 13951041, maiorPontuacao: 56, pontuacaoUltimaRodada: 56, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "sinceridade: qualidade maldita!", slug: require("./src/assets/escudos/sinceridade-qualidade-maldita.png"), backgroundColor: "#000000", textColor: "#bf1d17", pointsColor: "#bf1d17", id: 5342721, maiorPontuacao: 49, pontuacaoUltimaRodada: 49, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Skalabuta FC", slug: require("./src/assets/escudos/skalabuta-fc.png"), backgroundColor: "#000000", textColor: "#ffffff", pointsColor: "#ffffff", id: 25871781, maiorPontuacao: 63, pontuacaoUltimaRodada: 63, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Sporting Draga", slug: require("./src/assets/escudos/sporting-draga.png"), backgroundColor: "#000000", textColor: "#ff241d", pointsColor: "#ff241d", id: 810144, maiorPontuacao: 60, pontuacaoUltimaRodada: 60, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Tangamandapiense Social Clube", slug: require("./src/assets/escudos/tangamandapiense-social-clube.png"), backgroundColor: "#ffffff", textColor: "#4d004d", pointsColor: "#4d004d", id: 25867159, maiorPontuacao: 31, pontuacaoUltimaRodada: 31, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "tarcisiospfc", slug: require("./src/assets/escudos/tarcisiospfc.png"), backgroundColor: "#ff241d", textColor: "#ffffff", pointsColor: "#ffffff", id: 8917, maiorPontuacao: 38, pontuacaoUltimaRodada: 38, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Time do Igor FC", slug: require("./src/assets/escudos/time-do-igor-fc.png"), backgroundColor: "#ffcb00", textColor: "#000000", pointsColor: "#000000", id: 1160952, maiorPontuacao: 75, pontuacaoUltimaRodada: 75, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "U.C. Leões de Judá", slug: require("./src/assets/escudos/u-c-leoes-de-juda.png"), backgroundColor: "#000000", textColor: "#ffcb00", pointsColor: "#ffcb00", id: 14972226, maiorPontuacao: 47, pontuacaoUltimaRodada: 47, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "vernochi82", slug: require("./src/assets/escudos/vernochi82.png"), backgroundColor: "#a64b00", textColor: "#ff241d", pointsColor: "#ff241d", id: 25584876, maiorPontuacao: 9, pontuacaoUltimaRodada: 9, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "Victrola F.C.", slug: require("./src/assets/escudos/victrola-f-c.png"), backgroundColor: "#808080", textColor: "#bf1d17", pointsColor: "#bf1d17", id: 13946184, maiorPontuacao: 55, pontuacaoUltimaRodada: 55, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "VilãoFC", slug: require("./src/assets/escudos/vilaofc.png"), backgroundColor: "#000000", textColor: "#ffffff", pointsColor: "#ffffff", id: 2370283, maiorPontuacao: 68, pontuacaoUltimaRodada: 68, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
//             { name: "OTOPATAMAR cc", slug: require("./src/assets/escudos/otopatamar-cc.png"), backgroundColor: "#000000", textColor: "#bf1d17", pointsColor: "#bf1d17", id: 26126210, maiorPontuacao: 64, pontuacaoUltimaRodada: 64, pts: 0, atletas: [], pegouAtletas: false , numAtletasPontuando: 0, capitaoId: 0, distrital: false},
                            
//             // { name: "", backgroundColor: "#008000", textColor: "#008000", pointsColor: "#008000", id: 0, pts: -100 },
//             // { name: "", backgroundColor: "#008000", textColor: "#008000", pointsColor: "#008000", id: 0, pts: -101 },        
//           ]);
//     }
// }